
#include "ioc/ioc.hpp"
#include <set>
namespace threatlens::ioc { using namespace threatlens::core; std::string type_name(IocType t){switch(t){case IocType::ip:return"ip";case IocType::cidr:return"cidr";case IocType::domain:return"domain";case IocType::url:return"url";case IocType::hash:return"hash";default:return"unknown";}}
static std::string uncomment(std::string s){bool q=false;for(size_t i=0;i<s.size();++i){if(s[i]=='"')q=!q;if(!q&&(s[i]=='#'||(s[i]=='/'&&i+1<s.size()&&s[i+1]=='/')))return trim(s.substr(0,i));}return trim(s);} static std::map<std::string,std::string> attrs(const std::vector<std::string>&c){std::map<std::string,std::string> m;for(size_t i=1;i<c.size();++i){auto x=trim(c[i]);auto e=x.find('=');if(e!=std::string::npos)m[lower(trim(x.substr(0,e)))] = strip_quotes(x.substr(e+1));else if(i==1)m["severity"]=x;else if(i==2)m["confidence"]=x;}return m;}
Ioc normalize_ioc(std::string_view tok,std::string_view src){Ioc i;i.original=std::string(tok);i.source=std::string(src);auto t=strip_quotes(trim(tok));if(t.empty())return i;auto l=lower(t);if(starts_with(l,"allow:")){i.source+=":allow";t=t.substr(6);l=lower(t);}if(auto c=parse_cidr(t)){i.type=IocType::cidr;i.cidr=c;i.value=c->str();return i;}if(auto ip=parse_ipv4(t)){i.type=IocType::ip;i.ip=ip;i.value=ip->str();return i;}if(url_like(t)){i.type=IocType::url;i.value=normalize_url(t);return i;}if(hash_like(t)){i.type=IocType::hash;i.value=lower(t);return i;}if(domain_like(t)){i.type=IocType::domain;i.value=normalize_domain(t);return i;}i.value=sanitize_token(t);return i;}
core::Result<IocSet> parse_ioc_text(std::string_view text,std::string_view src){Result<IocSet> r;std::set<std::string> seen;std::istringstream in(std::string(text));std::string line;size_t n=0;while(std::getline(in,line)){++n;auto clean=uncomment(line);if(clean.empty())continue;char d=clean.find(',')!=std::string::npos?',':(clean.find(';')!=std::string::npos?';':' ');auto cols=split(clean,d,false);auto at=attrs(cols);auto i=normalize_ioc(cols.empty()?"":cols[0],src);if(i.type==IocType::unknown){r.diagnostics.add(ErrorCode::malformed,Severity::low,"unrecognized indicator",n);continue;}if(at.count("severity"))i.severity=parse_severity(at["severity"],i.severity);if(at.count("confidence")){try{i.confidence=std::stod(at["confidence"]);if(i.confidence>1.0)i.confidence/=100.0;}catch(...){}}bool allow=i.source.find(":allow")!=std::string::npos||at["list"]=="allow"||at["action"]=="allow";auto key=(allow?"a:":"b:")+type_name(i.type)+":"+i.value;if(!seen.insert(key).second){++r.value.duplicate_count;r.diagnostics.add(ErrorCode::duplicate,Severity::info,"duplicate indicator",n);continue;}if(allow)r.value.allowlist.push_back(i);else r.value.indicators.push_back(i);}r.value.diagnostics=r.diagnostics;return r;}
static bool mdomain(const packet::PacketMetadata&m,const std::string&d){for(auto&n:m.dns_names){auto x=normalize_domain(n);if(x==d||ends_with(x,"."+d))return true;}return false;} static bool hit(const Ioc&i,const packet::PacketMetadata&m,std::string&why){if(i.type==IocType::ip){if(m.src_ip==i.value){why="source ip";return true;}if(m.dst_ip==i.value){why="destination ip";return true;}}if(i.type==IocType::cidr&&i.cidr){auto s=parse_ipv4(m.src_ip),d=parse_ipv4(m.dst_ip);if(s&&i.cidr->contains(*s)){why="source cidr";return true;}if(d&&i.cidr->contains(*d)){why="destination cidr";return true;}}if(i.type==IocType::domain&&mdomain(m,i.value)){why="dns name";return true;}if(i.type==IocType::url){auto h=i.value;auto p=h.find("://");if(p!=std::string::npos){h=h.substr(p+3);h=h.substr(0,h.find('/'));}if(mdomain(m,h)){why="url host";return true;}}return false;}
bool is_allowed(const IocSet&s,const packet::PacketMetadata&m){std::string w;for(auto&a:s.allowlist)if(hit(a,m,w))return true;return false;} std::vector<IocMatch> match_packet_metadata(const IocSet&s,const std::vector<packet::PacketMetadata>&meta){std::vector<IocMatch> o;for(auto&m:meta){if(is_allowed(s,m))continue;for(auto&i:s.indicators){std::string w;if(hit(i,m,w))o.push_back({i,m,w});}}return o;} std::string summarize(const IocSet&s){std::map<IocType,int> c;for(auto&i:s.indicators)c[i.type]++;std::ostringstream o;o<<"indicators="<<s.indicators.size()<<" allowlist="<<s.allowlist.size()<<" duplicates="<<s.duplicate_count;for(auto&kv:c)o<<" "<<type_name(kv.first)<<"="<<kv.second;return o.str();} std::string matches_to_text(const std::vector<IocMatch>&m){std::ostringstream o;for(auto&x:m)o<<type_name(x.indicator.type)<<","<<x.indicator.value<<","<<x.reason<<","<<x.metadata.summary<<"\n";return o.str();}
}
